spring.application.name=peliculas-v4
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/intermodular
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jackson.property-naming-strategy=SNAKE_CASE